### ISSUE TITLE
文章内锚点

### ISSUE THREAD

**Issue by strongant** [SpringForAll/spring-guides-translation#118]
翻译文章内部的跳转不要指向原文，直接在翻译文章内加锚点跳转即可？

**Comment by dyc87112** [comment]
利用markdown的链接锚点进行跳转，比如：有一个链接是跳转到标题Gradle的，那么需要这么实现：

链接这样写 ：` [链接名](#maodian)`

要跳转到的标题这样写：`<h2 id="maodian">Gradle</h2>` ， 不能用传统的写法：`## Gradle`
