### ISSUE TITLE
翻译文章标题格式统一

### ISSUE THREAD

**Issue by strongant** [SpringForAll/spring-guides-translation#120]
翻译文章的一级、二级标题统一，有些小伙伴翻译的时候由于没有使用Typora导致同一级标题，有些使用二级标题，有些使用三级标题，导致翻译内容格式不统一！

**Comment by dyc87112** [comment]
1、校对和merge的人需要看一下标题的，不行的comment提示修改
2、如果后面还是有漏掉的，发现了就我们管理员直接维护下
