### ISSUE TITLE
校对的问题

### ISSUE THREAD

**Issue by chenzhijun** [SpringForAll/spring-guides-translation#121]
现在翻译的小伙伴非常多，所以导致可能上次提交的翻译文章PR，还没人校对(阻塞)，然后他又提了一个新的翻译申请PR，导致我们无法来合并新的翻译申请PR。

source下面的文件不删除，将所有翻译后待校对的文章先放到translated目录？ 然后大家想校对的话，可以直接fork仓库，修改校对再PR。

校对的原则： 一般翻译初稿应该是不会有太多问题，校对主要看语句是否更加适合汉语阅读习惯？文章是否有相应的代码错误，技术上的点错误漏掉？

是否可以考虑开辟一个校对小组，专门负责校队？可以让群里的小伙伴申请。校对小组只是主要负责校对，其他人如果想要校对也是可以校对的，他们合并就好。

**Comment by zaixiandemiao** [comment]
校对是不是由零散时间比较多、对Spring比较熟（专业术语润色?）的小伙伴来完成比较好啊，毕竟相当于把关的。

**Comment by dyc87112** [comment]
成立校对小组，由志峰负责，提供更加专业的校对~后续就开始招募和分配任务~
