### ISSUE TITLE
Batch YARN Application 翻译认领

### ISSUE THREAD

**Issue by UniKrau** [SpringForAll/spring-guides-translation#54]
# Batch YARN Application
# YARN  的批处理应用程序

This guide walks you through the process of executing a Spring Batch job on Hadoop YARN.

这篇文章主要是探讨Spring 批处理job 在Hadoop YARN上执行的过程

# What you’ll build
# 你将学会构建什么

You’ll build a simple Hadoop YARN application with Spring Hadoop, Spring Batch and Spring Boot.、
通过Spring Hadoop, Spring Batch and Spring Boot 构建一个简单Hadoop YARN 应用程序

# What you’ll need
# 你需要准备什么

* About 15 minutes 大概15分钟解决战斗
* A favorite text editor or IDE 文本编辑器或IDE
* [JDK 1.6](http://www.oracle.com/technetwork/java/javase/downloads/index.html) or later 需要[JDK 1.6](http://www.oracle.com/technetwork/java/javase/downloads/index.html) 以上的版本
* [Gradle 2.3+](http://www.gradle.org/downloads) or [ Maven 3.0+](https://maven.apache.org/download.cgi)
* You can also import the code straight into your IDE: 也可以将代码直接导入到IDE
  * [Spring Tool Suite (STS)](https://spring.io/guides/gs/sts)
  * [IntelliJ IDEA](https://spring.io/guides/gs/intellij-idea/)
     * Local single-node instance based on Hadoop 2.2.0 or later

# How to complete this guide 干货

Like most Spring [Getting Started guides](https://spring.io/guides), you can start from scratch and complete each step, or you can bypass basic setup steps that are already familiar to you. Either way, you end up with working code.

To **start from scratch** , move on to [Set up the project](https://spring.io/guides/gs/yarn-batch-processing/#scratch).
**新手**场，移步[配置工程](https://spring.io/guides/gs/yarn-batch-processing/#scratch)
To **skip the basics** , do the following:
**老司机**走起
* [Download](https://github.com/spring-guides/gs-yarn-batch-processing/archive/master.zip) and unzip the source repository for this guide, or clone it using [Git](https://spring.io/understanding/Git): 
 git clone [https://github.com/spring-guides/gs-yarn-batch-processing.git]
(https://github.com/spring-guides/gs-yarn-batch-processing.git)

* [下载](https://github.com/spring-guides/gs-yarn-batch-processing/archive/master.zip)源码然后使unzip 命令解压，或者使用[Git](https://spring.io/understanding/Git)拷贝一份源代码，拷贝命令：git clone [https://github.com/spring-guides/gs-yarn-batch-processing.git](https://github.com/spring-guides/gs-yarn-batch-processing.git)

* cd into gs-yarn-batch-processing/initial 使用cd 命令跳转到gs-yarn-batch-processing/initial 目录

* Jump ahead to [Create a Remote Batch Step](https://spring.io/guides/gs/yarn-batch-processing/#initial). 创建[远程批处理步骤](https://spring.io/guides/gs/yarn-batch-processing/#initial)

**When you’re finished**, you can check your results against the code in 
**以上步骤结束之后**， 可以在 gs-yarn-batch-processing/complete 目录下检查代码，

# Set up the project 配置工程
First you set up a basic build script. You can use any build system you like when building apps with Spring, but the code you need to work with [Gradle](http://gradle.org/) is included here. If you’re not familiar with it, refer to [Building Java Projects with Gradle](https://spring.io/guides/gs/gradle).
首先要配置编译脚本。Spring构建apps的时候可以使用的编译工具有很多，但是在这里需要用[Gradle](http://gradle.org/)编译代码。如果不熟悉，请参考[Gradle编译java工程](https://spring.io/guides/gs/gradle).

### Create the directory structure 目录结构

In a project directory of your choosing, create the following subdirectory structure:
在工程文件夹下，创建子文件夹

├── gs-yarn-batch-processing-appmaster
│   └── src
│       └── main
│           ├── resources
│           └── java
│               └── hello
│                   └── appmaster
├── gs-yarn-batch-processing-container
│   └── src
│       └── main
│           ├── resources
│           └── java
│               └── hello
│                   └── container
├── gs-yarn-batch-processing-client
│   └── src
│       └── main
│           ├── resources
│           └── java
│               └── hello
│                   └── client
└── gs-yarn-batch-processing-dist
    └── src
        └── test
            └── java
                └── hello

for example, with on *nix systems:
举个栗子，使用unix或者Linux系统的同学使用 mkdir -p 命令分别创建以上文件夹

mkdir -p gs-yarn-batch-processing-appmaster/src/main/resources
mkdir -p gs-yarn-batch-processing-appmaster/src/main/java/hello/appmaster
mkdir -p gs-yarn-batch-processing-container/src/main/resources
mkdir -p gs-yarn-batch-processing-container/src/main/java/hello/container
mkdir -p gs-yarn-batch-processing-client/src/main/resources
mkdir -p gs-yarn-batch-processing-client/src/main/java/hello/client
mkdir -p gs-yarn-batch-processing-dist/src/test/java/hello

### Create a Gradle build file 

Below is the [initial Gradle build file](https://github.com/spring-guides/gs-yarn-batch-processing/blob/master/initial/build.gradle). If you are using [Spring Tool Suite (STS)](https://spring.io/guides/gs/sts), you can import the guide directly.

[初始化Gradle编译文件 ](https://github.com/spring-guides/gs-yarn-batch-processing/blob/master/initial/build.gradle)。也可以用[Spring Tool Suite (STS)](https://spring.io/guides/gs/sts)工具直接导入源码

build.gradle

buildscript {
    repositories {
        maven { url "http://repo.spring.io/libs-release" }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.3.RELEASE")
    }
}

allprojects {
    apply plugin: 'base'
}

subprojects { subproject ->
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    version =  '0.1.0'
    repositories {
        mavenCentral()
        maven { url "http://repo.spring.io/libs-release" }
    }
    dependencies {
        compile("org.springframework.data:spring-yarn-boot:2.4.0.RELEASE")
    }
    task copyJars(type: Copy) {
        from "$buildDir/libs"
        into "$rootDir/gs-yarn-batch-processing-dist/target/gs-yarn-batch-processing-dist/"
        include "**/*.jar"
    }
    configurations {
        compile.exclude group: "org.slf4j", module: "slf4j-log4j12"
        runtime.exclude group: "org.slf4j", module: "slf4j-log4j12"
    }
    assemble.doLast {copyJars.execute()}
}

project('gs-yarn-batch-processing-client') {
    apply plugin: 'spring-boot'
}

project('gs-yarn-batch-processing-appmaster') {
    apply plugin: 'spring-boot'
    dependencies {
        compile("org.springframework.data:spring-yarn-batch:2.4.0.RELEASE")
        runtime("org.springframework.boot:spring-boot-starter-batch:1.3.3.RELEASE")
    }
}

project('gs-yarn-batch-processing-container') {
    apply plugin: 'spring-boot'
    dependencies {
        compile("org.springframework.data:spring-yarn-batch:2.4.0.RELEASE")
        runtime("org.springframework.boot:spring-boot-starter-batch:1.3.3.RELEASE")
    }
}

project('gs-yarn-batch-processing-dist') {
    dependencies {
        compile project(":gs-yarn-batch-processing-client")
        compile project(":gs-yarn-batch-processing-appmaster")
        compile project(":gs-yarn-batch-processing-container")
        testCompile("org.springframework.data:spring-yarn-boot-test:2.4.0.RELEASE")
        testCompile("org.hamcrest:hamcrest-core:1.2.1")
        testCompile("org.hamcrest:hamcrest-library:1.2.1")
    }
    test.dependsOn(':gs-yarn-batch-processing-client:assemble')
    test.dependsOn(':gs-yarn-batch-processing-appmaster:assemble')
    test.dependsOn(':gs-yarn-batch-processing-container:assemble')
    clean.doLast {ant.delete(dir: "target")}
}

task wrapper(type: Wrapper) {
    gradleVersion = '1.11'
}

In above gradle build file we simply create three different jars, each having classes for its specific role. These jars are then repackaged by Spring Boot’s gradle plugin to create an executable jars.
依照gradle 编译文件，简单的构建三个不同的jar包，Spring Boot’s gradle 插件会把这三个包编译成可执行jar包

You also need a settings.gradle file to define the sub-projects.
settings.gradle文件定义其子项目

settings.gradle 内容

include 'gs-yarn-batch-processing-client','gs-yarn-batch-processing-appmaster','gs-yarn-batch-processing-container','gs-yarn-batch-processing-dist'

### Spring 批处理介绍

Many batch processing problems can be solved with single threaded, single process jobs, so it is always a good idea to properly check if that meets your needs before thinking about more complex implementations. When you are ready to start implementing a job with some parallel processing, Spring Batch offers a range of options. At a high level there are two modes of parallel processing: single process, multi-threaded; and multi-process.

可以用单线程或进程的job解决批处理问题，因此处理许多复杂的问题的时候优可能会先考虑是否能用批处理模式解决。Spring Batch提供了很多并行处理方法解决这些问题。有两种高级层次多并行处理模型：单进程，多线程；多进程

Spring Hadoop contains a support for running Spring Batch jobs using YARN on a on a Hadoop cluster. For better parallel processing Spring Batch partitioned steps can be executed on YARN as remote steps.

在Hadoop YARN 计算框架的集群上 Spring Hadoop 支持Spring Batch 类型的job。为了更好的并行处理， Spring Batch 做了分区，而且在YARN上执行的时候采用remote steps的方式。

The starting point for running a Spring Batch Job on YARN is always the Application Master whether the job is just a simple job with or without partitioning. In the case when partitioning is not used, the whole job would run within the Application Master and no additional YARN containers would be launched. This may seem a bit odd, to run something on YARN without using containers, but one should remember that the Application Master is also just a resource allocated from the Hadoop cluster running in a YARN container.

要在YARN上运行Spring Batch Job 的关键地方在于Application Master能否判断这个job是不是简单类型的或者不要进行分区。job没有分区的时候，整个job都运行在 Application Master内并且不会启动额外的容器。好神奇的样子，竟然不要容器就能在YARN跑job，但是别忘了Application Master其实也是Hadoop 集群分配的资源，当然也是一个能运行在YARN上容器。

In order to run Spring Batch jobs on a Hadoop cluster, few constraints exists:
 要在Hadoop 集群上运行Spring Batch jobs，还是有些限制的
* Job Context - Application Master is the main entry point of running the job.
* Job Context - Job 上下文，Application Master是运行job的主要实体
* Job Repository - Application Master needs to have access to a repository which is located either in-memory or in a relational database. These are the two types natively supported by Spring Batch.
* Job Repository - Job 仓库， Application Master需要访问驻留在内存或者关系型数据库的仓库。显然Spring Batch是支持这两种。
* Remote Steps - Due to nature how Spring Batch partitioning works, remote steps need access to the job repository
* 远程工作集- 由于 Spring Batch有分区能力的基因，所以远程工作集需要访问工作仓库

Let’s take a quick look at how Spring Batch partitioning is handled. The concept of running a partitioned job involves three things, Remote Steps, Partition Handler and a Partitioner. If we do a little bit of oversimplification a remote step is like any other step from a user point of view. Spring Batch itself does not contain implementations for any proprietary grid or remoting fabrics. Spring Batch does however provide a useful implementation of PartitionHandler that executes Steps locally in separate threads of execution, using the TaskExecutor strategy from Spring. Spring Hadoop provides implementation to execute Steps remotely on a Hadoop cluster using YARN.

快速浏览Spring Batch 分区是怎样的机制，其理念是：一个分区好的job需要三样东西，第一 远程工作集，第二 分区处理器，第三 分区者。站在用户的角度来看，任何一个 remote step 都有点过于简化了。Spring Batch 本身不包含任何专门网格计算或者特殊远程过程调用实现。然而Spring Batch确实提供PartitionHandler的实现，PartitionHandler会根据Spring的TaskExecutor的策略，然后使用各自独立的线程运行工作集。Spring Hadoop针对Hadoop集群提供了远程工作集的实现。

### 创建远程批处理集

Here you create a PrintTasklet class.
需要一个PrintTasklet 类

gs-yarn-batch-processing-container/src/main/java/hello/container/PrintTasklet.java

package hello.container;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.scope.context.ChunkContext;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.batch.repeat.RepeatStatus;

public class PrintTasklet implements Tasklet {

	private static final Log log = LogFactory.getLog(PrintTasklet.class);

	@Override
	public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext)
			throws Exception {
		log.info("PrintTasklet says Hello");
		return RepeatStatus.FINISHED;
	}

}

A Tasklet in Spring Batch is one of the easiest concepts to use when something needs to be executed in a step as part of a job. This simple tasklet is serving the purpose of demonstrating how simple it is to execute a real `Partitioned Step`s on Hadoop YARN without introducing more complex job processing.

一个job的step当中，Tasklet接口是Spring Batch最简单通俗易懂的概念之一。这个tasklet目的只是简单示范一下真正Partitioned Step是如何执行的。当然就不用介绍如何处理复杂job处理啦

In the above PrintTasklet we simply write a log message when the Tasklet itself is executed.
在PrintTasklet类 就是些简单输出日志

Now it’s time to create a ContainerApplication class.
然后创建ContainerApplication 类

gs-yarn-batch-processing-container/src/main/java/hello/container/ContainerApplication.java

package hello.container;

import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.step.tasklet.Tasklet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.yarn.batch.config.EnableYarnRemoteBatchProcessing;

@Configuration
@EnableAutoConfiguration(exclude = { BatchAutoConfiguration.class })
@EnableYarnRemoteBatchProcessing
public class ContainerApplication {

	@Autowired
	private StepBuilderFactory stepBuilder;

	@Bean
	protected Tasklet tasklet() {
		return new PrintTasklet();
	}

	@Bean
	protected Step remoteStep() throws Exception {
		return stepBuilder
			.get("remoteStep")
			.tasklet(tasklet())
			.build();
	}

	public static void main(String[] args) {
		SpringApplication.run(ContainerApplication.class, args);
	}

}

* The @EnableYarnRemoteBatchProcessing annotation tells Spring to enable Batch processing for YARN Containers. Batch @EnableBatchProcessing is then automatically included which means all builders for JavaConfig are available. @EnableYarnRemoteBatchProcessing 注解 Spring为YARN 容器提供Batch处理的功能 @EnableBatchProcessing 自动使得JavaConfig的所有建造者都可用。

* We @AutoWired the step builder which is then used to create steps as beans.
* @AutoWired  step建造者把steps转换成beans
* We define PrintTasklet as a @Bean 把PrintTasklet转换成Bean
* We create a step as a @Bean and instruct it to execute a tasklet.
*  一个step变成bean以后就知道怎么执行一个tasklet了

Next we create an application.yml file for the container.
接下来为容器写一个 application.yml 文件

gs-yarn-batch-processing-container/src/main/resources/application.yml

格式如下

spring:
    batch:
        job:
            enabled: false
    hadoop:
        fsUri: hdfs://localhost:8020
    yarn:
        batch:
            enabled: true

 * We disable batch functionality in Spring Boot core to use YARN specific features.
* 在Spring Boot core里禁用batch功能，因此就可以使用YARN特性
* We add Hadoop configuration for HDFS. This can be customized for accessing a real cluster.
* 配置HDFS文件，在真实的集群里是可以自定义的
* We enable batch processing on YARN by using spring.yarn.batch.enabled property.
* 通过spring.yarn.batch.enabled property可以在YARN上使用批处理

### Create a Batch Job 创建一个批处理job

Here we create a AppmasterApplication class. 创建 AppmasterApplication 类

gs-yarn-batch-processing-appmaster/src/main/java/hello/appmaster/AppmasterApplication.java

package hello.appmaster;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParametersIncrementer;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.launch.support.RunIdIncrementer;
import org.springframework.batch.core.partition.PartitionHandler;
import org.springframework.batch.core.partition.support.Partitioner;
import org.springframework.batch.core.partition.support.SimplePartitioner;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.yarn.batch.config.EnableYarnBatchProcessing;
import org.springframework.yarn.batch.partition.StaticPartitionHandler;

@Configuration
@EnableAutoConfiguration
@EnableYarnBatchProcessing
public class AppmasterApplication {

	@Autowired
	private JobBuilderFactory jobFactory;

	@Autowired
	private StepBuilderFactory stepFactory;

	@Bean
	public Job job() throws Exception {
		return jobFactory.get("job")
			.incrementer(jobParametersIncrementer())
			.start(master())
			.build();
	}

	@Bean
	public JobParametersIncrementer jobParametersIncrementer() {
		return new RunIdIncrementer();
	}

	@Bean
	protected Step master() throws Exception {
		return stepFactory
			.get("master")
			.partitioner("remoteStep", partitioner())
			.partitionHandler(partitionHandler())
			.build();
	}

	@Bean
	protected Partitioner partitioner() {
		return new SimplePartitioner();
	}

	@Bean
	protected PartitionHandler partitionHandler() {
		StaticPartitionHandler handler = new StaticPartitionHandler();
		handler.setStepName("remoteStep");
		handler.setGridSize(2);
		return handler;
	}

	public static void main(String[] args) {
		SpringApplication.run(AppmasterApplication.class, args);
	}

}

* @EnableYarnBatchProcessing tells Spring to enable Batch processing for appmaster.
* @EnableYarnBatchProcessing 为appmaster启动Batch处理功能
* We @AutoWired builders for steps and jobs. 为steps和jobs提供建造者

Next we create an application.yml file for the appmaster.

gs-yarn-batch-processing-appmaster/src/main/resources/application.yml

spring:
    batch:
        job:
            enabled: false
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: gs-yarn-batch-processing
        applicationDir: /app/gs-yarn-batch-processing/
        batch:
            enabled: true
            name: job
            jobs:
              - name: job
                enabled: true
                next: true
        appmaster:
            keepContextAlive: false
            launchcontext:
                archiveFile: gs-yarn-batch-processing-container-0.1.0.jar

 * We disable batch functionality in Spring Boot core to use YARN specific features.
* 在Spring Boot core里禁用batch功能，因此就可以使用YARN特性
* We add Hadoop configuration for HDFS. This can be customized for accessing a real cluster.
* 配置HDFS文件，在真实的集群里是可以自定义的
* We enable batch processing on YARN by using spring.yarn.batch.enabled property.
* 通过spring.yarn.batch.enabled property可以在YARN上使用批处理
* We define a job named job to run automatically.
* 取个job的名字然后就能自动跑
* We enable a job named job and allow it to do a next operation.
*取个job的名字并且允许下一步操作

### Create a Yarn Client 创建Yarn客户端

Here we create a ClientApplication class.

创建 ClientApplication 类

gs-yarn-batch-processing-client/src/main/java/hello/client/ClientApplication.java

package hello.client;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.yarn.client.YarnClient;

@EnableAutoConfiguration
public class ClientApplication {

	public static void main(String[] args) {
		SpringApplication.run(ClientApplication.class, args)
			.getBean(YarnClient.class)
			.submitApplication();
	}

}

The ClientApplication is similar to what we’ve used in other guides and its only purpose is to submit a YARN application.
ClientApplication非常类似在其他指南的程序，不过这里的目的只是提交一个YARN application

Here you create an application.yml file for the client.

创建一个client application.yml 文件

gs-yarn-batch-processing-client/src/main/resources/application.yml

spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: gs-yarn-batch-processing
        applicationDir: /app/gs-yarn-batch-processing/
        client:
            files:
              - "file:target/gs-yarn-batch-processing-dist/gs-yarn-batch-processing-container-0.1.0.jar"
              - "file:target/gs-yarn-batch-processing-dist/gs-yarn-batch-processing-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: gs-yarn-batch-processing-appmaster-0.1.0.jar

* Here we simply defined all the files of the application that are needed for submission.
* 为application需要提交的，定义好了所有的文件
### Build the Application

For gradle simply execute the clean and build tasks.
使用简单粗暴的gradle命令：clean清空工作目录，build编译
./gradlew clean build

To skip existing tests if any:
跳过所有的单元测试
./gradlew clean build -x test

For maven simply execute the clean and package goals.
使用简单粗暴的Maven命令：clean清空工作目录，package打包
mvn clean package

To skip existing tests if any:
使用-DskipTests属性跳过单元测试
mvn clean package -DskipTests=true

Below listing shows files after a succesfull gradle build.
gradle 编译成功之后 在target里有以下三个jar包

gs-yarn-batch-processing-dist/target/gs-yarn-batch-processing-dist/gs-yarn-batch-processing-client-0.1.0.jar
gs-yarn-batch-processing-dist/target/gs-yarn-batch-processing-dist/gs-yarn-batch-processing-appmaster-0.1.0.jar
gs-yarn-batch-processing-dist/target/gs-yarn-batch-processing-dist/gs-yarn-batch-processing-container-0.1.0.jar

Run the Application 运行Application

Now that we’ve successfully compiled and packaged our application, it’s time to do the fun part and execute it on Hadoop YARN.
目前为止已经成功的编译打包了application了，该上Hadoop YARN上试试了

Simply run the executable client jar.
运行这个client jar包

$ cd gs-yarn-batch-processing-dist
$ java -jar target/gs-yarn-batch-processing-dist/gs-yarn-batch-processing-client-0.1.0.jar

If the application executes successfully we should be able to see two steps executed on a YARN.
在YARN可以看到两段执行过程如果这个程序没有出错

### Create a JUnit Test Class 创建一个单元测试类

Below is a class which can be used to execute this application as a JUnit test without running Hadoop cluster.以下这个执行应用程序的类可以作为单元测试类，并不需要在Hadoop集群上跑

gs-yarn-batch-processing-dist/src/test/java/hello/AppIT.java
package hello;

import static org.hamcrest.CoreMatchers.containsString;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThan;
import hello.client.ClientApplication;

import java.io.File;
import java.util.List;
import java.util.Scanner;

import org.apache.hadoop.yarn.api.records.YarnApplicationState;
import org.junit.Test;
import org.springframework.core.io.Resource;
import org.springframework.yarn.boot.test.junit.AbstractBootYarnClusterTests;
import org.springframework.yarn.test.context.MiniYarnClusterTest;
import org.springframework.yarn.test.junit.ApplicationInfo;
import org.springframework.yarn.test.support.ContainerLogUtils;

@MiniYarnClusterTest
public class AppIT extends AbstractBootYarnClusterTests {

	@Test
	public void testAppSubmission() throws Exception {

		ApplicationInfo info = submitApplicationAndWait(ClientApplication.class, new String[0]);
		assertThat(info.getYarnApplicationState(), is(YarnApplicationState.FINISHED));

		List<Resource> resources = ContainerLogUtils.queryContainerLogs(getYarnCluster(), info.getApplicationId());
		assertThat(resources, notNullValue());
		assertThat(resources.size(), is(6));

		for (Resource res : resources) {
			File file = res.getFile();
			if (file.getName().endsWith("stdout")) {
				// there has to be some content in stdout file
				assertThat(file.length(), greaterThan(0l));
				if (file.getName().equals("Container.stdout")) {
					Scanner scanner = new Scanner(file);
					String content = scanner.useDelimiter("\\A").next();
					scanner.close();
					// this is what container will log in stdout
					assertThat(content, containsString("PrintTasklet says Hello"));
				}
			} else if (file.getName().endsWith("stderr")) {
				String content = "";
				if (file.length() > 0) {
					Scanner scanner = new Scanner(file);
					content = scanner.useDelimiter("\\A").next();
					scanner.close();
				}
				// can't have anything in stderr files
				assertThat("stderr file is not empty: " + content, file.length(), is(0l));
			}
		}
	}
}

### Summary 总结一下

Congratulations! You’ve just developed a Spring YARN application executing a Spring Batch job!
恭喜了，可以开发Spring Batch job的Spring YARN程序了

**Comment by ucool2007** [comment]
# Batch YARN Application
# YARN  的批处理应用程序

This guide walks you through the process of executing a Spring Batch job on Hadoop YARN.

这篇文章主要是探讨Spring 批处理job 在Hadoop YARN上执行的过程

# What you’ll build
# 你将学会构建什么

You’ll build a simple Hadoop YARN application with Spring Hadoop, Spring Batch and Spring Boot.、
通过Spring Hadoop, Spring Batch and Spring Boot 构建一个简单Hadoop YARN 应用程序

# What you’ll need
# 你需要准备什么

* About 15 minutes 大概15分钟解决战斗
* A favorite text editor or IDE 文本编辑器或IDE
* [JDK 1.6](http://www.oracle.com/technetwork/java/javase/downloads/index.html) or later 需要[JDK 1.6](http://www.oracle.com/technetwork/java/javase/downloads/index.html) 以上的版本
* [Gradle 2.3+](http://www.gradle.org/downloads) or [ Maven 3.0+](https://maven.apache.org/download.cgi)
