### ISSUE TITLE
Building Java Projects with Maven 翻译认领

### ISSUE THREAD

**Issue by liqiangatshimodotstore** [SpringForAll/spring-guides-translation#57]
Building Java Projects with Maven 翻译认领

**Comment by ucool2007** [comment]
# Building Spring YARN Projects with Maven
# 用Maven构建Spring YARN 项目
This guide walks you through using Maven to build a simple Spring YARN project.
老司机带你走一遍，用Maven构建一个简单的Spring YARN 工程
### What you’ll build
你将学会构建什么
You’ll create a simple app and then build it using Maven.
创建一个简单的app然后用Maven构建之

In this guide we are not trying to create fully working YARN application, instead we focus on project and build model.
在这篇文章里不准备创建一个完整可用的YARN app，而是关注项目和构建模型
### What you’ll need
*  About 15 minutes 差不多15分钟搞定
*  A favorite text editor or IDE 文本编辑器或者IDE都行
* JDK 6 or later 支持JDK6 以上
# How to complete this guide
# 怎么撸完这篇文章
Like most Spring Getting Started guides, you can start from scratch and complete each step, or you can bypass basic setup steps that are already familiar to you. Either way, you end up with working code.
像大多数Spring 入门文章一样，即是新手或者老司机可以跳过已经熟悉的基本步骤，但是最后，程序是可以跑的

To** start from scratch**, move on to [Set up the project](https://spring.io/guides/gs/maven-yarn/#scratch)
**新手**，请移步[配置项目](https://spring.io/guides/gs/maven-yarn/#scratch)


To **skip the basics**, do the following:
老司机教程 如下：
* Download and unzip the source repository for this guide, or clone it using [Git](https://spring.io/understanding/Git): 
git clone https://github.com/spring-guides/gs-maven-yarn.git
 可以通过git源代码库下载并解压，或者使用git命令拷贝这个项目
* cd into gs-maven-yarn/initial 使用cd 命令跳到 gs-maven-yarn/initial目录
* Jump ahead to Understanding Maven Usage with Spring YARN.
跳转到 [Understanding Maven Usage with Spring YARN](https://spring.io/guides/gs/maven-yarn/#initial).

**When you’re finished**, you can check your results against the code in 

**当以上步骤完成**，可以到gs-maven-yarn/complete 目录检查代码

If you’re not familiar with gradle, refer to[ Building Java Projects with Maven](https://spring.io/guides/gs/maven).

如果不熟悉gradle工具，可以参考[ Building Java Projects with Maven](https://spring.io/guides/gs/maven)

# Set up the project 
# 配置这个项目

First you set up a Java project for Maven to build. To keep the focus on Maven, make the project as simple as possible for now.

首先用Maven构建一个java 工程，当然这个项目尽可能简单，因为重点是在Maven上

Create the directory structure
创建目录结构
In a project directory of your choosing, create the following subdirectory structure:
选好了工程目录以后，父目录下的子目录结构这样的：

├── gs-maven-yarn-appmaster
│   └── src
│       └── main
│           ├── resources
│           └── java
│               └── hello
│                   └── appmaster
├── gs-maven-yarn-container
│   └── src
│       └── main
│           ├── resources
│           └── java
│               └── hello
│                   └── container
├── gs-maven-yarn-client
│   └── src
│       └── main
│           ├── resources
│           └── java
│               └── hello
│                   └── client
└── gs-maven-yarn-dist

for example, on *nix systems, with:
举个栗子，在Unix或Linux系统下，使用mkdir -p 命令创建

mkdir -p gs-maven-yarn-appmaster/src/main/resources
mkdir -p gs-maven-yarn-appmaster/src/main/java/hello/appmaster
mkdir -p gs-maven-yarn-container/src/main/resources
mkdir -p gs-maven-yarn-container/src/main/java/hello/container
mkdir -p gs-maven-yarn-client/src/main/resources
mkdir -p gs-maven-yarn-client/src/main/java/hello/client
mkdir -p gs-maven-yarn-dist

Here you create a ContainerApplication class.
创建一个容器app类

_gs-maven-yarn-container/src/main/java/hello/container/ContainerApplication.java_

package hello.container;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;

@EnableAutoConfiguration
public class ContainerApplication {

	public static void main(String[] args) {
		SpringApplication.run(ContainerApplication.class, args);
	}

}

Here you create an AppmasterApplication class.
创建一个 Appmaster 类

gs-maven-yarn-appmaster/src/main/java/hello/appmaster/AppmasterApplication.java

package hello.appmaster;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;

@EnableAutoConfiguration
public class AppmasterApplication {

	public static void main(String[] args) {
		SpringApplication.run(AppmasterApplication.class, args);
	}

}

Here you create a ClientApplication class.
